name: Daily dev.fiftyone.ai Deploy
on:
  workflow_dispatch:
    inputs:
      deployer-branch:
        default: "main"
        description: "cloud-build-and-deploy branch to use"
        type: string
  schedule:
    # jobs run at UTC time, this should be 7:22 AM EST, every day Mon-Sat
    - cron: 22 11 * * 1-6

jobs:
  call-dev-cloud-build-and-deploy:
    uses: "voxel51/cloud-build-and-deploy/.github/workflows/dev-build-and-deploy.yml@main"
    with:
      deployer-branch: ${{ inputs.deployer-branch || 'main' }}
    secrets:
      FIFTYONE_SEGMENT_WRITE_KEY: ${{ secrets.FIFTYONE_SEGMENT_WRITE_KEY }}
      ORG_GITHUB_ACTIONS_SLACK_BOT_TOKEN: ${{ secrets.ORG_GITHUB_ACTIONS_SLACK_BOT_TOKEN }}
      ORG_GOOGLE_WORKLOAD_IDP: ${{ secrets.ORG_GOOGLE_WORKLOAD_IDP }}
      ORG_UPPTIME_SLACK_CHANNEL_ID: ${{ secrets.ORG_UPPTIME_SLACK_CHANNEL_ID }}
      RO_CBAD_FG_PAT: ${{ secrets.RO_CBAD_FG_PAT }}
