name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
      - feat/*
      - main
      - release/v[0-9]+.[0-9]+.[0-9]+

jobs:
  modified-files:
    runs-on: ubuntu-latest
    outputs:
      app-changes: ${{ steps.base-filter.outputs.app }}
      e2e-changes: ${{ steps.base-filter.outputs.e2e-pw }}
      fiftyone-changes: ${{ steps.base-filter.outputs.fiftyone }}
      teams-app-changes: ${{ steps.teams-app-filter.outputs.teams-app }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: base-filter
        with:
          filters: |
            app:
              - 'app/**'
            e2e-pw:
              - 'e2e-pw/**'
            fiftyone:
              - 'fiftyone/**'
              - 'requirements/**'
              - 'tests/**'
              - 'requirements.txt'
              - 'setup.py'
      - uses: dorny/paths-filter@v3
        id: teams-app-filter
        with:
          predicate-quantifier: 'every'
          filters: |
            teams-app:
              - 'teams-app/**'
              - '!teams-app/Dockerfile'
  build:
    needs: modified-files
    if: ${{ needs.modified-files.outputs.app-changes == 'true' || needs.modified-files.outputs.fiftyone-changes == 'true' || needs.modified-files.outputs.teams-app-changes == 'true' }}
    uses: ./.github/workflows/build.yml

  e2e:
    needs: modified-files
    if: ${{ needs.modified-files.outputs.app-changes == 'true' || needs.modified-files.outputs.e2e-changes == 'true' || needs.modified-files.outputs.fiftyone-changes == 'true' || needs.modified-files.outputs.teams-app-changes == 'true' }}
    uses: ./.github/workflows/e2e.yml

  lint:
    needs: modified-files
    if: ${{ needs.modified-files.outputs.app-changes == 'true' || needs.modified-files.outputs.fiftyone-changes == 'true' || needs.modified-files.outputs.teams-app-changes == 'true' }}
    uses: ./.github/workflows/lint-app.yml

  teams:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: voxel51
          repo: fiftyone-teams
          github_token: ${{ secrets.FIFTYONE_GITHUB_TOKEN }}
          github_user: voxel51-bot
          workflow_file_name: merge-oss.yml
          ref: develop
          wait_interval: 20
          client_payload: |
            {
              "author": "${{ github.event.pull_request.user.login }}",
              "branch": "${{ github.head_ref || github.ref_name }}",
              "pr": ${{ github.event.pull_request.number }}
            }
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

  test:
    needs: modified-files
    if: ${{ needs.modified-files.outputs.app-changes == 'true' || needs.modified-files.outputs.fiftyone-changes == 'true' || needs.modified-files.outputs.teams-app-changes == 'true' }}
    uses: ./.github/workflows/test.yml

  all-tests:
    runs-on: ubuntu-latest
    needs: [build, lint, test, e2e]
    if: always()
    steps:
      - run: sh -c ${{
          (needs.build.result == 'success' || needs.build.result == 'skipped') &&
          (needs.lint.result == 'success' || needs.lint.result == 'skipped') &&
          (needs.test.result == 'success' || needs.test.result == 'skipped') }}
